spring:
  application:
    name: DayDreamer
    security:
      jwt:
        access_token:
          secret: ${JWT_ACCESS_TOKEN_SECRET}
          expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
        refresh_token:
          secret: ${JWT_REFRESH_TOKEN_SECRET}
          expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
      sms-otp:
        twilio-account-sid: ${TWILIO_ACCOUNT_SID}
        twilio-auth-token: ${TWILIO_AUTH_TOKEN}
        twilio-service-sid: ${TWILIO_SERVICE_SID}
      payos:
        payos_client_id: 756c099f-7489-4068-b954-1eadbb35aeb4
        payos_api_key: 8ae97506-bd1f-4cf6-aa7b-ffcbb46ab204
        payos_checksum_key: c9dd8d2b7b28586a3cbf8be3a693b7386b4b1ca9e1dfb4529d8c23d88514e75a
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
